# Generated by Django 3.1.7 on 2021-05-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipzon', '0002_auto_20210529_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default='', max_length=50),
        ),
    ]
