# Generated by Django 3.1.7 on 2021-06-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipzon', '0004_auto_20210529_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
