# Generated by Django 3.1.7 on 2021-06-02 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipzon', '0005_auto_20210601_0913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catagory',
            new_name='category',
        ),
    ]
