# Generated by Django 3.1.7 on 2021-06-05 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipzon', '0009_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
